apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: buildkit
data:
  buildkitd.toml: |
    root = "/var/lib/buildkit"
    debug = false
    [worker.oci]
      max-parallelism = 32
      gckeepstorage = "70%"
      enabled = true
      gc = true
      snapshotter = "overlayfs"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd-arm
  name: buildkitd-arm
  namespace: buildkit
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: buildkitd-arm
  template:
    metadata:
      labels:
        app: buildkitd-arm
    spec:
      containers:
        - image: "moby/buildkit:v0.23.0"
          imagePullPolicy: Always
          name: buildkitd
          args:
            - --addr
            - tcp://0.0.0.0:1234
            - --root
            - /var/lib/buildkit
          env:
            - name: BUILDKIT_HOST
              value: tcp://127.0.0.1:1234
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: "500Mi"
              cpu: "300m"
            requests:
              memory: "400Mi"
              cpu: "200m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/buildkit/buildkitd.toml
              subPath: buildkitd.toml
            - name: var-lib-buildkit
              mountPath: /var/lib/buildkit
      volumes:
        - name: config
          configMap:
            name: buildkitd-config
            items:
              - key: buildkitd.toml
                path: buildkitd.toml
        - name: var-lib-buildkit
          persistentVolumeClaim:
            claimName: pv-volume
---

apiVersion: v1
kind: Service
metadata:
  name: buildkitd-arm
  namespace: buildkit
spec:
  selector:
    app: buildkitd-arm
  ports:
    - name: buildkit
      protocol: TCP
      port: 1234
      targetPort: 1234

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  hostPath:
    path: "/data/buildkit"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume
  namespace: buildkit
spec:
  volumeName: pv-volume
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi