apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: buildkit
data:
  buildkitd.toml: |
    root = "/var/lib/buildkit"
    debug = false
    [worker.oci]
      max-parallelism = 16
      gckeepstorage = "80%"
      enabled = true
      gc = true
      snapshotter = "overlayfs"
    
    [grpc]
      max_recv_msg_size = 67108864  # 64MB
      max_send_msg_size = 67108864  # 64MB
    
    [registry."docker.io"]
      mirrors = ["https://registry-1.docker.io"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd-arm
  name: buildkitd-arm
  namespace: buildkit
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: buildkitd-arm
  template:
    metadata:
      labels:
        app: buildkitd-arm
    spec:
      containers:
        - image: "moby/buildkit:v0.23.0"
          imagePullPolicy: Always
          name: buildkitd
          args:
            - --addr
            - tcp://0.0.0.0:1234
            - --root
            - /var/lib/buildkit
          env:
            - name: BUILDKIT_HOST
              value: tcp://127.0.0.1:1234
          readinessProbe:
            exec:
              command:
                - buildctl
                - debug
                - workers
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "500m"
          securityContext:
            privileged: true
          volumeMounts:
            - name: config
              mountPath: /etc/buildkit/buildkitd.toml
              subPath: buildkitd.toml
            # - name: var-lib-buildkit
            #   mountPath: /var/lib/buildkit
      volumes:
        - name: config
          configMap:
            name: buildkitd-config
            items:
              - key: buildkitd.toml
                path: buildkitd.toml
        # - name: var-lib-buildkit
        #   persistentVolumeClaim:
        #     claimName: pv-volume
---

apiVersion: v1
kind: Service
metadata:
  name: buildkitd-arm
  namespace: buildkit
spec:
  selector:
    app: buildkitd-arm
  ports:
    - name: buildkit
      protocol: TCP
      port: 1234
      targetPort: 1234

---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-volume
# spec:
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteMany
#   storageClassName: ""
#   hostPath:
#     path: "/data/buildkit"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pv-volume
#   namespace: buildkit
# spec:
#   volumeName: pv-volume
#   accessModes:
#     - ReadWriteMany
#   storageClassName: ""
#   resources:
#     requests:
#       storage: 10Gi

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: buildkitd-arm-hpa
  namespace: buildkit
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: buildkitd-arm
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60